spring.application.name=node
server.port=8080

# Redis Config (Default local dev)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# gRPC Config (Porta mTLS padrao da rede)
grpc.server.port=443

# Ativar Virtual Threads (Project Loom) no Java 21 para escalabilidade
spring.threads.virtual.enabled=true
