# PowerDNS Slave Configuration
# IMPORTANTE: Substitua SUA_SENHA_AQUI pelo valor real que está no seu .env

# Backend configuration
launch=gpgsql
gpgsql-host=db.local
gpgsql-port=5432
gpgsql-dbname=pdns
gpgsql-user=pdns_user
gpgsql-password=SUA_SENHA_AQUI

# DNS Server settings
local-address=0.0.0.0
local-port=5353

# Master / Slave / Supermaster configs 
slave=yes
superslave=yes

# Por segurança, no slave nós desabilitamos a API e o painel (tudo é gerenciado no master)
api=no
webserver=no

