# PowerDNS Slave Configuration

# Backend configuration
launch=gpgsql
gpgsql-host=db
gpgsql-port=5432
gpgsql-dbname=pdns
# gpgsql-user e gpgsql-password passados via docker-compose (PDNS_gpgsql_user / PDNS_gpgsql_password)

# DNS Server settings
local-address=0.0.0.0
local-port=53

# Master / Slave / Supermaster configs 
# (Ativados via docker-compose env vars: PDNS_slave=yes e PDNS_superslave=yes)

# Por segurança, no slave nós desabilitamos a API e o painel (tudo é gerenciado no master)
api=no
webserver=no
